{{- if or (not .Values.llm.existingSecret) (not .Values.embedding.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patient360-copilot.generatedSecretName" . }}
  labels:
    {{- include "patient360-copilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.llm.existingSecret }}
  LLM_API_KEY: {{ .Values.llm.apiKey | quote }}
  {{- end }}
  {{- if not .Values.embedding.existingSecret }}
  EMBEDDING_API_KEY: {{ .Values.embedding.apiKey | quote }}
  {{- end }}
{{- end }}
