replicaCount: 1

image:
  repository: vinchar/patient360-copilot
  tag: 0.1.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  streamlitPort: 8501
  apiPort: 8080

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  data:
    enabled: true
    size: 2Gi
    storageClassName: ""
    accessModes:
      - ReadWriteOnce

llm:
  baseUrl: ""
  model: ""
  apiKey: ""
  existingSecret: ""
  existingSecretKey: LLM_API_KEY
  sslVerify: true
  timeoutSeconds: 30

embedding:
  model: ""
  baseUrl: ""
  apiKey: ""
  existingSecret: ""
  existingSecretKey: EMBEDDING_API_KEY
  sslVerify: true

chroma:
  mode: http
  host: ""
  port: 443
  ssl: true
  sslVerify: true
  tenant: default_tenant
  database: default_database


env:
  logLevel: INFO
  loadPersistedRuntimeSettings: "true"
  runtimeSettingsPath: /app/data/config/runtime_settings.json
  hfHome: /app/data/cache/huggingface
  transformersCache: /app/data/cache/huggingface/transformers
  sentenceTransformersHome: /app/data/cache/sentence-transformers
  xdgCacheHome: /app/data/cache
  streamlitGatherUsageStats: "false"
  anonymizedTelemetry: "False"

ezua:
  virtualService:
    enabled: true
    endpoint: patient360-copilot.${DOMAIN_NAME}
    domain: ${DOMAIN_NAME}
    istioGateway: istio-system/ezaf-gateway
